name: ${name}
version: ${version}
main: ${main}
folia-supported: true
api-version: ${apiVersion}
load: STARTUP
description: A unique mining feature which removes the need to generate ores, and allows economy changes on the fly.
authors: [ d15c07d, VolmitSoftware ]
website: VolmitSoftware.com
softdepend:
  - PlaceholderAPI
commands:
  hiddenore:
    description: HiddenOre base command.
    usage: /hiddenore [config|debug|language]
permissions:
  hiddenore.debugdump:
    description: Allows creating and optionally uploading diagnostic reports.
    default: op
  hiddenore.language.self:
    description: Allows choosing your own language for this plugin.
    default: true
  hiddenore.admin:
    description: Allows use of all Mining plugin commands
    default: op
